export default{
    std1:{
        id : 1,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Professor',
        year: '0000',
        imgUrl : '', 
    },
    std2:{
        id : 2,
        name: 'John Doe',
        email : 'jdoe@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std3:{
        id : 3,
        name: 'Student 3',
        email : 'std3@walsh.edu',
        role : 'Professor', 
        year: '0000',
        imgUrl : '', 
    },
    std4:{
        id : 4,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore', 
        imgUrl : '', 
    },
    std5:{
        id : 5,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std6:{
        id : 6,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std7:{
        id : 7,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std8:{
        id : 8,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std9:{
        id : 9,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std10:{
        id : 10,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : '',  
    },
    std11:{
        id : 11,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Professor',
        year: '0000',
        imgUrl : '',  
    },

}