export default{
    std1:{
        id : 1,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light', 
    },
    std2:{
        id : 2,
        name: 'John Doe',
        email : 'jdoe@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std3:{
        id : 3,
        name: 'Student 3',
        email : 'std3@walsh.edu',
        role : 'Student',
        year : 'Sophomore', 
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light', 
    },
    std4:{
        id : 4,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore', 
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light', 
    },
    std5:{
        id : 5,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std6:{
        id : 6,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std7:{
        id : 7,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std8:{
        id : 8,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std9:{
        id : 9,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std10:{
        id : 10,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },
    std11:{
        id : 11,
        name: 'Sagar Subedi',
        email : 'ssubedi1@walsh.edu',
        role : 'Student',
        year : 'Sophomore',
        imgUrl : 'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Blank&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light',  
    },

}